### ISSUE TITLE
Can you please tell me more about how you generate those datasets?

### ISSUE THREAD

**Issue by twang2218** [gertjanssenswillen/eventdataR#2]
I'm currently working on a datasets generator R script for `eventdataR` to put into `data-raw`, and make the datasets generation process automatically, so we can add more datasets easier. I will submit a pull request later for it. For now, I need a little bit more information about how you generate those datasets.

## Did you remove any columns after `read_xes()`?

I noticed the `BPIC15_1` has `15` columns, however, the data frame I retrieved from `read_xes()` for `BPIC15_1` is `30` columns. What's your intention to drop those columns? Should I drop those columns when I create the generator script? If so, what's pattern should I follow for which column should be dropped?

Are there any other steps you have done to the datasets?

## Are `BPIC15_1_imported` and `csv_example` committed by accidentally?

I found those files in the repo, however, I didn't find them in the released package. Has anything been updated but not pushed to this repo?

BTW, generator script is currently in my forked branch (still work in progress): <https://github.com/twang2218/eventdataR/blob/add_dataset_generator/data-raw/data.R>

**Comment by gertjanssenswillen** [comment]
- there is no specific reason these columns have been removed, probably this file is only a sample of the published version (https://data.4tu.nl/repository/uuid:31a308ef-c844-48da-948c-305d167a0ec1). There is no problem in including all the variables.
- There has been a clean-up recently, these datasets have become obsolete and were removed from the CRAN-version. I will make sure to set things right immediately.
- Thanks for creating the generator script. Feel free to ask for more information if needed.
